### ISSUE TITLE
Transcribe.py output problem

### ISSUE THREAD

**Issue by akakakakakaa** [homink/deepspeech.pytorch.ko#1]
안녕하세요. 경희대학교 김만수입니다.

STT에 관심이 있어 검색하던 중, 여기를 찾아 트레이닝 시켜보았는데요.

필요한 패키지들을 다운받고, 러닝을 완료하였고, deepspeech_final_pth.tar가 성공적으로 생성되었습니다.

그 후, transribe.py를 실행하였을 때, 

{"output": [{"transcription": "      "}], "_meta": {"language_model": {"name": null}, "acoustic_model": {"version": "0.0.1", "hidden_layers": 5, "name": "deepspeech_final.pth.tar", "hidden_size": 800, "rnn_type": "gru"}, "decoder": {"alpha": null, "beta": null, "lm": false, "type": "greedy"}}}

다음과 같은 output을 얻게 되었습니다. 왜 이런 문제가 생기는지 짐작이 안가 질문올립니다.
답변해주시면 감사하겠습니다.

**Comment by homink** [comment]
안녕하세요

transcribe.py에 입력을 정상적으로 주셨다면 [{"transcription": " "}] 여기 쌍따옴표 안에 인식된 결과가 보여야 할 것입니다.
인식된 결과 없는 것으로 추측컨데 입력으로 넣어주신 음성신호가 인식되기에 적합하지 않은 것으로 판단됩니다. 이는 audio sampling rate 및 volume, 발화 표현 등 훈련에 사용된 음성신호가 입력에 넣어준 음성신호와 유사한지, 또는 훈련 시 사용된 옵션들들이 적합한지등에 따라 여려가지 요인이 있을 수 있습니다.

transcribe.py 내에 로그를 찍어가며 분석을 해보시는게 좋을 것 같네요

**Comment by akakakakakaa** [comment]
홈페이지에 공유해주신 발화데이터를 그대로 학습한 후, 예제로 올려주신 명령어를 그대로 사용하였는데요.

한번 말씀해주신 데로 transcribe.py에서 확인해보도록 하겠습니다.

혹시 현재 소스코드 외에 추가적인 작업이 있다면 가르쳐주시면 감사하겠습니다!

**Comment by akakakakakaa** [comment]
train.py 188번째 줄에서,
labels = str(''.join(json.load(label_file))) 을 labels = json.load(label_file)로 변경하니 훈련이 완벽하게 되었습니다. json.load에 의해서 element가 3byte인 list을 받았는데, join에 의해서 1byte 단위의 리스트로 입력이 들어와서 훈련에서부터 문제가 생김을 알 수 있었습니다.

**Comment by homink** [comment]
label_file 입력을 저는 사용해보지 않았습니다만 join에 의해 리스트 데이터 형태가 변경되었다면 label_file의 format이 달라 그럴 수 도 있을 것 같습니다. 해당 코드는 원본 repository인 deepspeech.pytorch에서도 동일하니 참고하세요.

https://github.com/SeanNaren/deepspeech.pytorch/blob/655cd586de798b3656c9c52242a11cde3d8a6bd4/train.py#L211
